# Generated by Django 5.1.2 on 2024-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_adminblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminblog',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
